import Head from "next/head";
import Card from "../components/Card";
import styles from "../styles/Home.module.scss";
import { useState, useEffect } from "react";

export default function Home() {
  const [data, setData] = useState(null);

  const getData = async () => {
    try {
      const res = await fetch("https://api.adviceslip.com/advice");
      const data = await res.json();
      setData(data.slip);
    } catch (error) {
      console.log("error", error);
    }
  };
  useEffect(() => {
    getData();
    return () => {};
  }, []);

  return (
    <>
      <Head>
        <title>Advice generator app</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.wrapper}>
        {data && <Card data={data} action={getData} />}
      </main>
    </>
  );
}
